export const doctorsSeedData = [
  {
    name: "Doctor James Marrs",
    quailifications: "BMBS",
    bio: "James graduated from London Medical School.James will be your doctor if you book a general checkup.",
    url: "https://i.imgur.com/esqZ9VF.png",
    image: "client/src/images/DrJMarrs.png",
    services: [],
    appointments: [],
  },
  {
    name: "Doctor Anne Kerrins",
    quailifications: "BMBS",
    bio: "Anne graduated from London Medical School. Anne will be your doctor for STD testing .",
    url: "https://i.imgur.com/puPHJ2h.jpg",
    image: "client/src/images/NurseJackie.jpg",
    services: [],
    appointments: [],
  },
  {
    name: "Doctor Antony Long",
    quailifications: "BMBS",
    bio: "Antony graduated from London Medical School. Antony will be your doctor for blood testing. ",
    url: "https://i.imgur.com/LABOwcd.png",
    image: "client/src/images/DrALong.png",
    services: [],
    appointments: [],
  },
  {
    name: "Doctor Tom Briody",
    quailifications: "BMBS",
    bio: "Tom graduated from London Medical School. Tom will be your doctor for travel vaccinations",
    url: "https://i.imgur.com/pjTtyvP.png",
    image: "client/src/images/DrTBriody.png",
    services: [],
    appointments: [],
  },
  {
    name: "Doctor Arjun Doel",
    quailifications: "BMBS",
    bio: "Arjun graduated from London Medical School. Arjun will be in charge of covid testing and vaccinations.",
    url: "https://i.imgur.com/unDZGTX.png",
    image: "client/src/images/DrADoel.png",
    services: [],
    appointments: [],
  },
  {
    name: "Doctor Doogie Howser.",
    quailifications: "MD",
    bio: "Christian graduated from London Medical School. Christian will be your doctor for wart removal.",
    url: "https://i.imgur.com/jsJf7CT.png",
    image: "client/src/images/DrDHowser.png",
    services: [],
    appointments: [],
  },
];
